tools/level_editor/project.vala, tools/level_editor/sprite_import_dialog.vala
Now the editor it's able to use sphere colliders on sprites importer
=> circle importer: finishes

tools/level_editor/project.vala
Added a basic check for duplicate extensions to prevent the duplicate "png" issue#131 previously reported.
=> added check for duplicate extensions

tools/level_editor/level_editor.vala, tools/level_editor/project_browser.vala
Let me know if I missed any or need to fix anything.
=> added suggested and destructive actions

docs/index.rst, docs/installing_crown/hardware_requirements.rst, docs/installing_crown/index.rst, docs/installing_crown/installing_on_linux.rst, docs/installing_crown/installing_on_windows.rst, docs/introduction.rst
=> docs: add installation guides

docs/changelog.rst, src/lua/lua_stack.cpp
=> lua: check for validity first, then type

docs/changelog.rst, samples/core/editors/level_editor/level_editor.lua, src/lua/lua_api.cpp, src/lua/lua_environment.cpp, src/world/world.cpp, src/world/world.h, tools/level_editor/sound.vala, tools/level_editor/unit.vala
Handles a variety of issues when dealing with many objects in a level, both in tools and in the runtime.
=> tools: many objects

docs/changelog.rst, tools/level_editor/level.vala, tools/level_editor/level_editor.vala, tools/level_editor/sound.vala, tools/level_editor/unit.vala
Also send frame() once, at the end.
=> tools: accumulate then send in bulk

tools/level_editor/unit.vala
=> tools: spawn unit directly if it has a prefab

docs/changelog.rst, src/world/physics_world_bullet.cpp
=> world: activate body after setting new transform

tools/level_editor/level_editor.vala, tools/level_editor/project_browser.vala
=> tools: force project-browser panel to show when revealing resources

samples/core/units/light.unit
Also make sure it has a sensible default range.
=> samples: core: make omni the default light type

docs/changelog.rst, src/world/material_manager.cpp
=> resource: access the correct index

tools/level_editor/level_editor.vala, tools/level_editor/project.vala, tools/level_editor/project_browser.vala, tools/resource/state_machine_resource.vala, tools/resource/types.vala
=> tools: mesh/sprite animation state machine

docs/changelog.rst, src/resource/shader_resource.cpp
=> resource: stop merging static_compile

tools/level_editor/deploy_dialog.vala, tools/level_editor/panel_new_project.vala, tools/widgets/input_file.vala
=> tools: stop using GtkFileChooserButton

tools/level_editor/deploy_dialog.vala, tools/level_editor/level_editor.vala, tools/level_editor/panel_new_project.vala, tools/widgets/save_resource_dialog.vala
Removed int GTK4. Use equivalent plain string.
Part-of: #383
=> tools: stop using Gtk.STYLE_CLASS_*

tools/level_editor/project.vala, tools/widgets/open_resource_dialog.vala, tools/widgets/save_resource_dialog.vala
FileChooser.set_current_folder() takes a GLib.File in GTK4.
Part-of: #383
=> tools: use set_current_folder_file()

tools/level_editor/properties_view.vala
Follow-up to a5c458f01
Part-of: #195
=> tools: stop using GtkWidget event signals

tools/level_editor/level_tree_view.vala
=> tools: fix attemp to index nil

tools/resource/mesh_resource_fbx.vala
=> tools: only create anim component if animated and new skeleton

src/core/json/sjson.cpp, src/core/unit_tests.cpp
=> core: fix parsing of verbatims strings

src/world/world.cpp
=> world: actually remove the instance

src/world/world.cpp
=> world: populate _units and _unit_resources

tools/level_editor/level_editor.vala, tools/level_editor/properties_view.vala
=> tools: fix inspecting sound sources
